# frozen_string_literal: true

# This is auto-generated by Datastar. DO NOT EDIT.
module Datastar
  module Consts
    DATASTAR_KEY = 'datastar'
    VERSION = '1.0.0-RC.1'

    # The default duration for retrying SSE on connection reset. This is part of the underlying retry mechanism of SSE.
    DEFAULT_SSE_RETRY_DURATION = 1000

    # Should elements be patched using the ViewTransition API?
    DEFAULT_ELEMENTS_USE_VIEW_TRANSITIONS = false

    # Should a given set of signals patch if they are missing?
    DEFAULT_PATCH_SIGNALS_ONLY_IF_MISSING = false

    module ElementPatchMode

      # Morphs the element into the existing element.
      OUTER = 'outer';

      # Replaces the inner HTML of the existing element.
      INNER = 'inner';

      # Removes the existing element.
      REMOVE = 'remove';

      # Replaces the existing element with the new element.
      REPLACE = 'replace';

      # Prepends the element inside to the existing element.
      PREPEND = 'prepend';

      # Appends the element inside the existing element.
      APPEND = 'append';

      # Inserts the element before the existing element.
      BEFORE = 'before';

      # Inserts the element after the existing element.
      AFTER = 'after';
    end


    # The mode in which an element is patched into the DOM.
    DEFAULT_ELEMENT_PATCH_MODE = ElementPatchMode::OUTER

    # Dataline literals.
    SELECTOR_DATALINE_LITERAL = 'selector'
    MODE_DATALINE_LITERAL = 'mode'
    ELEMENTS_DATALINE_LITERAL = 'elements'
    USE_VIEW_TRANSITION_DATALINE_LITERAL = 'useViewTransition'
    SIGNALS_DATALINE_LITERAL = 'signals'
    ONLY_IF_MISSING_DATALINE_LITERAL = 'onlyIfMissing'
  end
end