# frozen_string_literal: true

# This is auto-generated by Datastar. DO NOT EDIT.
module Datastar
  module Consts
    DATASTAR_KEY = 'datastar'
    VERSION = '1.0.0-beta.11'

    # The default duration for retrying SSE on connection reset. This is part of the underlying retry mechanism of SSE.
    DEFAULT_SSE_RETRY_DURATION = 1000

    # Should elements be merged using the ViewTransition API?
    DEFAULT_ELEMENTS_USE_VIEW_TRANSITIONS = false

    # Should a given set of signals merge if they are missing?
    DEFAULT_MERGE_SIGNALS_ONLY_IF_MISSING = false


    # The mode in which an element is patched into the DOM.
    DEFAULT_ELEMENT_PATCH_MODE = ElementPatchMode::OUTER

    # Dataline literals.
    SELECTOR_DATALINE_LITERAL = 'selector'
    MODE_DATALINE_LITERAL = 'mode'
    ELEMENTS_DATALINE_LITERAL = 'elements'
    USE_VIEW_TRANSITION_DATALINE_LITERAL = 'useViewTransition'
    SIGNALS_DATALINE_LITERAL = 'signals'
    ONLY_IF_MISSING_DATALINE_LITERAL = 'onlyIfMissing'
  end
end